feat: Handle wildcard `#` in base path for message bus handler matching
edgexfoundry/device-sdk-c pull request #525
Opened 2024-11-28 15:05 UTC by FelixTing

The single-level wildcard `+` is not supported because it increases complexity, and there is currently no requirement for it.
fix: #523 

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-c/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2024-12-02 13:41 UTC, iain-anderson requested changes
Think it would be better to add `bool ignore_tail` to the `edgex_bus_endpoint_t` structure and check for the wildcard ending in `edgex_bus_register_handler` - then we can just do something like `if (ep->ignore_tail ? iot_data_list_length (tail) > iot_data_list_length (ep->params) : iot_data_list_length (tail) == iot_data_list_length (ep->params))` in `edgex_bus_match_handler`

2024-12-02 13:42 UTC, iain-anderson commented on src/c/bus.c
> +      iot_data_free (tail);
:+1:

2024-12-04 16:35 UTC, iain-anderson commented
looks alright except that you won't be able to use the feature for capturing path elements as parameters in combination with the wildcard - is this okay for our requirements?

2024-12-04 18:07 UTC, FelixTing commented
> looks alright except that you won't be able to use the feature for capturing path elements as parameters in combination with the wildcard - is this okay for our requirements?

https://github.com/edgexfoundry/device-sdk-c/pull/520/files#r1853237371
The requirement is to subscribe to topics such as the following, in order to receive update notifications for both private and common configurations.
- edgex/configs/edgex/v4/device-random/#
- edgex/configs/edgex/v4/core-common-config-bootstrapper/all-services/#
- edgex/configs/edgex/v4/core-common-config-bootstrapper/device-services/#

2024-12-05 11:11 UTC, iain-anderson approved these changes

2024-12-06 00:11 UTC, merged